//! End-to-end parity: Markdown in, HTML out, against measured Go output.
//!
//! Where `render_parity.rs` holds the parser constant to isolate the renderer,
//! this runs the whole pipeline — `run_with` against Go's `Run` — over the same
//! 1,449 cases. A failure here that `render_parity` does not also report is a
//! parser bug; one that both report is the renderer's.
//!
//! Generated by `tools/genrender/gen_test.go.txt`.

use blackfriday::html::{HtmlRenderer, HtmlRendererParameters};
use blackfriday::markdown::{run_with, Options};
use blackfriday::{Extensions, HtmlFlags};

const FIXTURE: &str = include_str!("fixtures/go-render.txt");

fn opt_bytes(s: &str) -> Option<Vec<u8>> {
    let rest = s.strip_prefix('x')?;
    Some(raw_hex(rest))
}

fn raw_hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn string(s: &str) -> String {
    String::from_utf8(opt_bytes(s).unwrap_or_default()).unwrap()
}

/// One document, its configuration, and what Go produced from it.
#[derive(Default)]
struct Case {
    config: String,
    sample: String,
    source: Vec<u8>,
    extensions: Extensions,
    params: HtmlRendererParameters,
    want: Vec<u8>,
}

fn cases() -> Vec<Case> {
    let mut out: Vec<Case> = Vec::new();
    for line in FIXTURE.lines() {
        let f: Vec<&str> = line.split(' ').collect();
        match f[0] {
            "C" => out.push(Case {
                config: f[2].to_string(),
                sample: String::from_utf8(raw_hex(f[3])).unwrap(),
                ..Default::default()
            }),
            "S" => {
                let case = out.last_mut().unwrap();
                case.extensions = Extensions::from_bits_retain(f[2].parse().unwrap());
                case.source = raw_hex(f.get(3).copied().unwrap_or(""));
            }
            "P" => {
                let case = out.last_mut().unwrap();
                case.params = HtmlRendererParameters {
                    flags: HtmlFlags::from_bits_retain(f[2].parse().unwrap()),
                    absolute_prefix: string(f[3]),
                    footnote_anchor_prefix: string(f[4]),
                    footnote_return_link_contents: string(f[5]),
                    heading_id_prefix: string(f[6]),
                    heading_id_suffix: string(f[7]),
                    heading_level_offset: f[8].parse().unwrap(),
                    title: string(f[9]),
                    css: string(f[10]),
                    icon: string(f[11]),
                };
            }
            "O" => {
                let case = out.last_mut().unwrap();
                case.want = raw_hex(f.get(2).copied().unwrap_or(""));
            }
            _ => {}
        }
    }
    out
}

#[test]
fn run_matches_go_end_to_end() {
    let cases = cases();
    assert_eq!(cases.len(), 1449, "fixture did not parse cleanly");

    let mut failures: Vec<String> = Vec::new();
    for case in &cases {
        let mut renderer = HtmlRenderer::new(case.params.clone());
        let got = run_with(
            &case.source,
            Options::none().with_extensions(case.extensions),
            &mut renderer,
        );
        if got != case.want {
            failures.push(format!(
                "[{}] {}\n  source: {:?}\n  want:   {:?}\n  got:    {:?}",
                case.config,
                case.sample,
                String::from_utf8_lossy(&case.source),
                String::from_utf8_lossy(&case.want),
                String::from_utf8_lossy(&got),
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} cases diverge:\n\n{}",
        failures.len(),
        cases.len(),
        failures
            .iter()
            .take(8)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n\n")
    );
}
