//! Renderer parity against measured Go output.
//!
//! The port's inline parser does not exist yet, so there is no way to turn
//! Markdown into a syntax tree on this side. This test takes the tree Go's
//! parser produced — dumped field by field in walk order — rebuilds it in an
//! [`Arena`], renders it, and compares against the HTML Go rendered from the
//! same tree. The parser is held constant, so any difference is the renderer's.
//!
//! 1,449 cases: 69 documents (46 hand-written, 23 taken from upstream's own
//! `testdata/`) across 21 renderer configurations.
//!
//! Generated by `tools/genrender/gen_test.go.txt`.

use blackfriday::html::{HtmlRenderer, HtmlRendererParameters};
use blackfriday::markdown::Renderer;
use blackfriday::node::{Arena, NodeId, NodeType, WalkStatus, Walker};
use blackfriday::{CellAlignFlags, HtmlFlags, ListType};

const FIXTURE: &str = include_str!("fixtures/go-render.txt");

/// Decodes the generator's `-` for nil, `x…` for hex-encoded bytes.
fn opt_bytes(s: &str) -> Option<Vec<u8>> {
    let rest = s.strip_prefix('x')?;
    Some(
        (0..rest.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&rest[i..i + 2], 16).unwrap())
            .collect(),
    )
}

/// The same, for fields Go cannot leave nil.
fn bytes(s: &str) -> Vec<u8> {
    opt_bytes(s).unwrap_or_default()
}

/// Plain hex, with no nil marker — the rendered-output column.
fn raw_hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn string(s: &str) -> String {
    String::from_utf8(bytes(s)).unwrap()
}

fn node_type(n: i32) -> NodeType {
    match n {
        0 => NodeType::Document,
        1 => NodeType::BlockQuote,
        2 => NodeType::List,
        3 => NodeType::Item,
        4 => NodeType::Paragraph,
        5 => NodeType::Heading,
        6 => NodeType::HorizontalRule,
        7 => NodeType::Emph,
        8 => NodeType::Strong,
        9 => NodeType::Del,
        10 => NodeType::Link,
        11 => NodeType::Image,
        12 => NodeType::Text,
        13 => NodeType::HTMLBlock,
        14 => NodeType::CodeBlock,
        15 => NodeType::Softbreak,
        16 => NodeType::Hardbreak,
        17 => NodeType::Code,
        18 => NodeType::HTMLSpan,
        19 => NodeType::Table,
        20 => NodeType::TableCell,
        21 => NodeType::TableHead,
        22 => NodeType::TableBody,
        23 => NodeType::TableRow,
        _ => panic!("unknown node type {n}"),
    }
}

/// One rebuilt document, ready to render.
struct Case {
    config: String,
    sample: String,
    arena: Arena,
    root: Option<NodeId>,
    params: HtmlRendererParameters,
    want: Vec<u8>,
}

/// Rebuilds every case in the fixture.
///
/// Nodes arrive in walk order with a depth column, which is enough: a node at
/// depth `d` is a child of the most recent node at depth `d - 1`.
fn cases() -> Vec<Case> {
    let mut out: Vec<Case> = Vec::new();
    let mut stack: Vec<NodeId> = Vec::new();

    for line in FIXTURE.lines() {
        let f: Vec<&str> = line.split(' ').collect();
        match f[0] {
            "C" => {
                out.push(Case {
                    config: f[2].to_string(),
                    sample: string(&format!("x{}", f[3])),
                    arena: Arena::new(),
                    root: None,
                    params: HtmlRendererParameters::default(),
                    want: Vec::new(),
                });
                stack.clear();
            }
            "N" => {
                let case = out.last_mut().unwrap();
                let depth: usize = f[2].parse().unwrap();
                let t = node_type(f[3].parse().unwrap());
                let id = case.arena.new_node(t);
                {
                    let n = case.arena.get_mut(id);
                    n.literal = bytes(f[4]);
                    n.heading.level = f[5].parse().unwrap();
                    n.heading.heading_id = bytes(f[6]);
                    n.heading.is_titleblock = f[7] == "true";
                    n.list.list_flags = ListType::from_bits_retain(f[8].parse().unwrap());
                    n.list.tight = f[9] == "true";
                    n.list.ref_link = opt_bytes(f[10]);
                    n.list.is_footnotes_list = f[11] == "true";
                    n.link.destination = bytes(f[12]);
                    n.link.title = opt_bytes(f[13]);
                    n.link.note_id = f[14].parse().unwrap();
                    n.code_block.info = bytes(f[15]);
                    n.table_cell.is_header = f[16] == "true";
                    n.table_cell.align = CellAlignFlags::from_bits_retain(f[17].parse().unwrap());
                }
                stack.truncate(depth);
                match stack.last() {
                    Some(&parent) => case.arena.append_child(parent, id),
                    None => case.root = Some(id),
                }
                stack.push(id);
            }
            "P" => {
                let case = out.last_mut().unwrap();
                case.params = HtmlRendererParameters {
                    flags: HtmlFlags::from_bits_retain(f[2].parse().unwrap()),
                    absolute_prefix: string(f[3]),
                    footnote_anchor_prefix: string(f[4]),
                    footnote_return_link_contents: string(f[5]),
                    heading_id_prefix: string(f[6]),
                    heading_id_suffix: string(f[7]),
                    heading_level_offset: f[8].parse().unwrap(),
                    title: string(f[9]),
                    css: string(f[10]),
                    icon: string(f[11]),
                };
            }
            "O" => {
                let case = out.last_mut().unwrap();
                case.want = raw_hex(f.get(2).copied().unwrap_or(""));
            }
            _ => {}
        }
    }
    out
}

/// Runs the three renderer entry points the way `Run` does.
fn render(case: &mut Case) -> Vec<u8> {
    let mut r = HtmlRenderer::new(case.params.clone());
    let mut out = Vec::new();
    let root = case.root.expect("every case has a Document node");
    r.render_header(&mut out, &mut case.arena, root);
    let mut walker = Walker::new(root);
    while let Some((node, entering)) = walker.current() {
        let status = r.render_node(&mut out, &case.arena, node, entering);
        walker.advance(&case.arena, status);
    }
    r.render_footer(&mut out, &case.arena, root);
    out
}

#[test]
fn renderer_matches_go_on_every_case() {
    let mut cases = cases();
    assert_eq!(cases.len(), 1449, "fixture did not parse cleanly");

    let mut failures: Vec<String> = Vec::new();
    for case in &mut cases {
        let want = case.want.clone();
        let got = render(case);
        if got != want {
            failures.push(format!(
                "[{}] {}\n  want: {:?}\n  got:  {:?}",
                case.config,
                case.sample,
                String::from_utf8_lossy(&want),
                String::from_utf8_lossy(&got),
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} cases diverge:\n\n{}",
        failures.len(),
        cases.len(),
        failures
            .iter()
            .take(6)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n\n")
    );
}

#[test]
fn the_corpus_covers_every_node_type_upstream_can_build() {
    // A renderer test that never rendered a table would pass for the wrong
    // reason, so assert the corpus actually reaches every node type.
    //
    // Every type but one. `Softbreak` is declared in node.go and handled in
    // RenderNode, but nothing in blackfriday v2 ever constructs one — grep the
    // package and the only non-test hits are the declaration, the String()
    // entry and the render arm. The port carries the arm anyway, since a
    // caller building its own tree can still reach it.
    let cases = cases();
    let mut seen = [false; 24];
    seen[NodeType::Softbreak as usize] = true;
    for case in &cases {
        let mut walker = Walker::new(case.root.unwrap());
        while let Some((node, entering)) = walker.current() {
            seen[case.arena[node].node_type as usize] = true;
            walker.advance(&case.arena, WalkStatus::GoToNext);
            let _ = entering;
        }
    }
    let missing: Vec<usize> = (0..24).filter(|&i| !seen[i]).collect();
    assert!(
        missing.is_empty(),
        "node types never exercised: {missing:?}"
    );
}
