// Generates src/unicode_tables.rs: the exact code-point sets blackfriday's
// SanitizedAnchorName depends on, read out of Go's own unicode tables.
//
// Why generate rather than use Rust's std:
//
//   - Go's unicode.IsLetter is General_Category L. Rust's char::is_alphabetic
//     is the Alphabetic property, which additionally includes Nl and
//     Other_Alphabetic. Measured against Go 1.23.5 / Rust 1.97.1 that is
//     11,171 extra code points -- combining marks, mostly -- which Go drops
//     from an anchor name and Rust would keep.
//   - Go's unicode.ToLower is simple case mapping. Rust's to_lowercase is full
//     case mapping and can yield more than one char (U+0130 is the only such
//     case inside this set).
//   - Embedding the tables also decouples the port from whichever Unicode
//     version a given Rust toolchain ships, so the answer does not drift.
package main

import (
	"fmt"
	"os"
	"runtime"
	"unicode"
	"unicode/utf8"
)

type rng struct{ lo, hi rune }

func main() {
	var pred []rune
	type pair struct{ from, to rune }
	var lowers []pair

	for r := rune(0); r <= 0x10FFFF; r++ {
		if r >= 0xD800 && r <= 0xDFFF {
			continue // surrogates are not scalar values; Rust has no char for them
		}
		if !utf8.ValidRune(r) {
			continue
		}
		if unicode.IsLetter(r) || unicode.IsNumber(r) {
			pred = append(pred, r)
			if lo := unicode.ToLower(r); lo != r {
				lowers = append(lowers, pair{r, lo})
			}
		}
	}

	var ranges []rng
	for i, r := range pred {
		if i > 0 && r == ranges[len(ranges)-1].hi+1 {
			ranges[len(ranges)-1].hi = r
			continue
		}
		ranges = append(ranges, rng{r, r})
	}

	out, err := os.Create("../../src/unicode_tables.rs")
	if err != nil {
		panic(err)
	}
	defer out.Close()

	fmt.Fprintf(out, `//! Unicode tables for `+"`SanitizedAnchorName`"+`.
//!
//! Generated by `+"`tools/genunicode`"+` from Go %s / Unicode %s.
//! Do not edit by hand; re-run the generator instead.
//!
//! These are transcribed out of Go rather than taken from Rust's std because
//! the two disagree, and the port has to match Go:
//!
//! - Go's `+"`unicode.IsLetter`"+` is General_Category L. Rust's
//!   `+"`char::is_alphabetic`"+` is the Alphabetic property, which also covers
//!   Nl and Other_Alphabetic. Measured across the whole code space that is
//!   **%d extra code points** Rust would call letters and Go would not --
//!   combining marks, mostly. Go drops those from an anchor name; a port built
//!   on `+"`is_alphabetic`"+` would keep them.
//! - Go's `+"`unicode.ToLower`"+` is *simple* case mapping. Rust's
//!   `+"`to_lowercase`"+` is *full* case mapping and may yield more than one
//!   char. Within this set U+0130 is the only such case.
//!
//! Embedding the tables also means the result does not shift when a Rust
//! toolchain updates its own Unicode version.

/// Inclusive ranges where Go's `+"`unicode.IsLetter(r) || unicode.IsNumber(r)`"+`
/// is true.
static LETTER_OR_NUMBER: [(u32, u32); %d] = [
`, runtime.Version(), unicode.Version, rustOnlyCount, len(ranges))

	for _, r := range ranges {
		fmt.Fprintf(out, "    (0x%04X, 0x%04X),\n", r.lo, r.hi)
	}

	fmt.Fprintf(out, `];

/// Go's simple lowercase mapping, for the code points in
/// [`+"`LETTER_OR_NUMBER`"+`] where it is not the identity.
static SIMPLE_LOWER: [(u32, u32); %d] = [
`, len(lowers))

	for _, p := range lowers {
		fmt.Fprintf(out, "    (0x%04X, 0x%04X),\n", p.from, p.to)
	}

	fmt.Fprint(out, `];

/// Go's `+"`unicode.IsLetter(r) || unicode.IsNumber(r)`"+`.
pub(crate) fn is_letter_or_number(c: char) -> bool {
    let cp = c as u32;
    LETTER_OR_NUMBER
        .binary_search_by(|&(lo, hi)| {
            if cp < lo {
                std::cmp::Ordering::Greater
            } else if cp > hi {
                std::cmp::Ordering::Less
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

/// Go's `+"`unicode.ToLower`"+` (simple case mapping).
///
/// Returns the input unchanged when there is no mapping, matching Go.
pub(crate) fn simple_to_lower(c: char) -> char {
    let cp = c as u32;
    match SIMPLE_LOWER.binary_search_by_key(&cp, |&(from, _)| from) {
        Ok(i) => char::from_u32(SIMPLE_LOWER[i].1).unwrap_or(c),
        Err(_) => c,
    }
}
`)

	fmt.Fprintf(os.Stderr, "wrote %d ranges, %d lower mappings (Unicode %s)\n",
		len(ranges), len(lowers), unicode.Version)
}

// rustOnlyCount is the number of code points for which Rust's
// char::is_alphabetic() || char::is_numeric() is true but Go's
// unicode.IsLetter(r) || unicode.IsNumber(r) is false.
//
// Go cannot compute Rust's answer, so this is a measured constant. It was
// obtained by dumping both predicates across the whole code space and diffing:
// Go's set proved to be a strict subset of Rust's, with zero code points in
// the other direction. Re-measure with tools/genunicode/measure.md if the
// toolchains move.
const rustOnlyCount = 11171
